TEXTS = {
    "nav_home": {"CN": "主页", "EN": "Home"},
    "nav_intro": {"CN": "项目介绍", "EN": "Introduction"},
    "nav_model": {"CN": "模型推理", "EN": "Model Inference"},
    "nav_history": {"CN": "历史记录", "EN": "History"},
    "nav_not_logged_in": {"CN": "未登录", "EN": "Not Logged In"},
    "nav_logout": {"CN": "退出登录", "EN": "Logout"},
    "nav_change_password": {"CN": "修改密码", "EN": "Change Password"},
    "home_welcome": {
        "CN": "欢迎使用 LPDP-RiR 系统",
        "EN": "Welcome to LPDP-RiR System",
    },
    "intro_title": {"CN": "项目介绍", "EN": "Project Introduction"},
    "intro_content": {
        "CN": "这是一个用于医疗图像分析的系统...",
        "EN": "This is a system for medical image analysis...",
    },
    "history_title": {"CN": "历史记录", "EN": "History Records"},
    "col_id": {"CN": "序号", "EN": "ID"},
    "col_time": {"CN": "记录时间", "EN": "Time"},
    "col_path": {"CN": "文件夹路径", "EN": "Path"},
    "btn_open_folder": {"CN": "打开所在文件夹", "EN": "Open Folder"},
    "btn_view_report": {"CN": "查看报告", "EN": "View Report"},
    "btn_refresh": {"CN": "刷新", "EN": "Refresh"},
    "msg_select_record": {
        "CN": "请先选择一条记录",
        "EN": "Please select a record first",
    },
    "msg_folder_not_exist": {"CN": "文件夹不存在", "EN": "Folder does not exist"},
    "msg_report_not_found": {"CN": "未找到报告文件", "EN": "Report file not found"},
    "title_info": {"CN": "提示", "EN": "Info"},
    "title_error": {"CN": "错误", "EN": "Error"},
    "btn_import": {"CN": "导入数据", "EN": "Import Data"},
    "btn_analyze": {"CN": "数据分析", "EN": "Analyze Data"},
    "btn_visualize": {"CN": "3D可视化", "EN": "3D Visualization"},
    "btn_unet": {"CN": "传统U-Net分析", "EN": "Traditional U-Net"},
    "btn_export": {"CN": "导出报告", "EN": "Export Report"},
    "header_input": {"CN": "输入数据", "EN": "Input Data"},
    "header_output": {"CN": "输出结果", "EN": "Output Result"},
    "label_result_type": {"CN": "结果类型:", "EN": "Result Type:"},
    "label_slice_index": {"CN": "切片索引:", "EN": "Slice Index:"},
    "label_description": {"CN": "结果说明:", "EN": "Description:"},
    "desc_default": {"CN": "请先进行分析...", "EN": "Please analyze first..."},
    "group_report": {"CN": "报告", "EN": "Report"},
    "msg_import_success": {"CN": "数据加载完成", "EN": "Data loaded"},
    "msg_import_fail": {"CN": "导入数据失败", "EN": "Import failed"},
    "msg_no_data": {"CN": "请先导入数据", "EN": "Please import data first"},
    "title_select_file": {"CN": "选择3D数据文件", "EN": "Select 3D Data File"},
    "desc_overlay": {
        "CN": "叠加图: 原始图像 + 预测掩码 + 概率热力图",
        "EN": "Overlay: Original + Mask + Heatmap",
    },
    "desc_mask": {
        "CN": "预测掩码: 多类别分割结果 (灰度值对应类别)",
        "EN": "Mask: Multi-class Segmentation",
    },
    "desc_binary": {
        "CN": "二值化结果: 仅前景/背景 (经过后处理)",
        "EN": "Binary: Foreground/Background (Post-processed)",
    },
    "desc_color": {
        "CN": "彩色掩码: 不同颜色代表不同类别",
        "EN": "Color Mask: Classes by Color",
    },
    "desc_prob_c0": {
        "CN": "概率图 (背景): 模型预测为背景的置信度",
        "EN": "Prob Map (Background): Confidence",
    },
    "desc_prob_c1": {
        "CN": "概率图 (前景): 模型预测为前景的置信度",
        "EN": "Prob Map (Foreground): Confidence",
    },
    "desc_acx_unet": {"CN": "传统U-NET结果", "EN": "Traditional U-Net Result"},
    "log_loading": {"CN": "正在加载数据: {}...", "EN": "Loading data: {}..."},
    "log_generating_slices": {
        "CN": "正在生成切片预览...",
        "EN": "Generating slice preview...",
    },
    "log_loaded": {
        "CN": "数据加载完成. 共 {} 张切片.",
        "EN": "Data loaded. Total {} slices.",
    },
    "log_input_dir": {"CN": "输入目录: {}", "EN": "Input directory: {}"},
    "log_error": {"CN": "错误: {}", "EN": "Error: {}"},
    "log_start_analysis": {"CN": "开始分析...", "EN": "Starting analysis..."},
    "log_no_path": {
        "CN": "错误: 未找到导入的文件路径",
        "EN": "Error: Import path not found",
    },
    "log_no_script": {
        "CN": "错误: 未找到模型脚本: {}",
        "EN": "Error: Model script not found: {}",
    },
    "log_executing": {"CN": "正在执行命令: {}", "EN": "Executing command: {}"},
    "login_title": {"CN": "登录系统", "EN": "Login System"},
    "login_welcome": {"CN": "欢迎登录", "EN": "Welcome Login"},
    "label_username": {"CN": "用户名:", "EN": "Username:"},
    "label_password": {"CN": "密  码:", "EN": "Password:"},
    "btn_login": {"CN": "登录", "EN": "Login"},
    "link_register": {"CN": "注册新用户", "EN": "Register New User"},
    "link_change_password": {"CN": "修改密码", "EN": "Change Password"},
    "msg_enter_user_pass": {
        "CN": "请输入用户名和密码",
        "EN": "Please enter username and password",
    },
    "msg_user_not_exist": {"CN": "用户不存在", "EN": "User does not exist"},
    "msg_user_not_reg": {
        "CN": "该用户尚未注册。是否立即前往注册？",
        "EN": "User not registered. Register now?",
    },
    "title_login_fail": {"CN": "登录失败", "EN": "Login Failed"},
    "msg_pass_wrong": {
        "CN": "密码错误，请重试",
        "EN": "Incorrect password, please try again",
    },
    "msg_welcome_user": {"CN": "欢迎回来, {}!", "EN": "Welcome back, {}!"},
    "remember_me": {"CN": "记住我", "EN": "Remember Me"},
    "reg_title": {"CN": "注册新用户", "EN": "Register New User"},
    "label_confirm": {"CN": "确认密码:", "EN": "Confirm Password:"},
    "btn_register": {"CN": "注册", "EN": "Register"},
    "link_login": {
        "CN": "已有账户？返回登录",
        "EN": "Already have an account? Back to Login",
    },
    "msg_enter_username": {"CN": "请输入用户名", "EN": "Please enter username"},
    "msg_enter_password": {"CN": "请输入密码", "EN": "Please enter password"},
    "msg_pass_mismatch": {"CN": "两次输入的密码不一致", "EN": "Passwords do not match"},
    "msg_reg_success": {
        "CN": "用户 {} 注册成功！即将跳转至登录页面。",
        "EN": "User {} registered successfully! Redirecting to login.",
    },
    "msg_reg_fail": {
        "CN": "注册失败：用户名已存在或输入非法",
        "EN": "Registration failed: Username exists or invalid input",
    },
    "cp_title": {"CN": "修改密码", "EN": "Change Password"},
    "label_old_pass": {"CN": "旧密码:", "EN": "Old Password:"},
    "label_new_pass": {"CN": "新密码:", "EN": "New Password:"},
    "label_confirm_new": {"CN": "确认新密码:", "EN": "Confirm New Password:"},
    "btn_change_pass": {"CN": "修改密码", "EN": "Change Password"},
    "btn_back": {"CN": "返回", "EN": "Back"},
    "msg_enter_old_pass": {"CN": "请输入旧密码", "EN": "Please enter old password"},
    "msg_enter_new_pass": {"CN": "请输入新密码", "EN": "Please enter new password"},
    "msg_new_pass_mismatch": {
        "CN": "两次输入的新密码不一致",
        "EN": "New passwords do not match",
    },
    "msg_change_pass_success": {
        "CN": "密码修改成功！请使用新密码重新登录。",
        "EN": "Password changed! Please login with new password.",
    },
    "msg_change_pass_fail": {
        "CN": "修改失败：用户名不存在或旧密码错误",
        "EN": "Failed: Username not found or old password incorrect",
    },
    "lang_switch": {"CN": "English", "EN": "中文"},
    "title_success": {"CN": "成功", "EN": "Success"},
    "title_warning": {"CN": "提示", "EN": "Warning"},
    "theme_switch": {"CN": "切换主题", "EN": "Theme"},
    "label_language": {"CN": "语言", "EN": "Language"},
    "label_theme": {"CN": "主题", "EN": "Theme"},
    "theme_extra_light": {"CN": "极浅医疗蓝", "EN": "Extra Light Medical Blue"},
    "theme_standard": {"CN": "标准医疗蓝", "EN": "Standard Medical Blue"},
    "theme_bright": {"CN": "明亮医疗蓝", "EN": "Bright Medical Blue"},
    "theme_soothing": {"CN": "柔和医疗蓝", "EN": "Soothing Medical Blue"},
    "theme_primary": {"CN": "主色医疗蓝", "EN": "Medical Blue Primary"},
    "theme_night": {"CN": "夜间模式蓝灰", "EN": "Night Mode Medical Blue Gray"},
}


def get_text(key, lang="CN"):
    return TEXTS.get(key, {}).get(lang, key)
